name: CI

on:
  push:
    branches:
     - main

    paths:
      - default.nix
      - ops-agent/default.nix
      - npins/*

  pull_request:
    branches:
     - main

    paths:
      - default.nix
      - ops-agent/default.nix
      - npins/*

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        architecture:
          - system: x86_64-linux
            runs-on: ubuntu-latest
          - system: aarch64-linux
            runs-on: ubuntu-24.04-arm

    name: Build - ${{ matrix.architecture.system }}
    runs-on: ${{ matrix.architecture.runs-on }}

    steps:
      - uses: actions/checkout@v4

      - uses: samueldr/lix-gha-installer-action@v2025-02-26.prerelease

      - uses: cachix/cachix-action@v16
        with:
          name: drakon64-nixos-ops-agent
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build
        run: |
          nix-build -A ops-agent
          echo "STORE_PATH=$(nix eval --raw --file default.nix ops-agent)" >> "$GITHUB_ENV"

      - name: Push to Cachix
        run: echo "$STORE_PATH" | cachix push drakon64-nixos-ops-agent

      - name: Pin in Cachix
        run: cachix pin drakon64-nixos-ops-agent ${{ matrix.architecture.system }} "$STORE_PATH" --keep-revisions 1
