name: CI

on:
  push:
    branches:
     - main

  pull_request:
    branches:
     - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: samueldr/lix-gha-installer-action@v2025-02-26.prerelease

      - uses: cachix/cachix-action@v16
        with:
          name: drakon64-nixos-ops-agent
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: nix-build -A ops-agent
